---  
  - name: gather_facts
    gather_facts:

  - name: Tag - Setup
    ansible.builtin.import_tasks:
      file: tag_setup.yml
    tags:
      - setup
      - baseline
      - never
  
  - name: Tag - Start
    ansible.builtin.import_tasks:
      file: tag_start.yml
    tags:
      - start
      - run
      - never

  - name: Tag - Stop
    ansible.builtin.import_tasks:
      file: tag_stop.yml
    tags:
      - stop
      - kill
      - never

  - name: Tag - Backup
    ansible.builtin.import_tasks:
      file: tag_backup.yml
    tags:
      - backup
      - never

  - name: Tag - Update
    ansible.builtin.import_tasks:
      file: tag_update.yml
    tags:
      - update
      - upgrade
      - never

  - name: Tag - Remove
    ansible.builtin.import_tasks:
      file: tag_remove.yml
    tags:
      - remove
      - never

  - name: Tag - Purge
    ansible.builtin.import_tasks:
      file: tag_purge.yml
    tags:
      - purge
      - never